"""create project update images table

Revision ID: 6a114f596907
Revises: c85a8ab1e380
Create Date: 2026-09-02 13:54:10.967152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a114f596907'
down_revision: Union[str, Sequence[str], None] = 'c85a8ab1e380'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_update_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_update_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_update_id'], ['project_updates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_update_images_id'), 'project_update_images', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_update_images_id'), table_name='project_update_images')
    op.drop_table('project_update_images')
    # ### end Alembic commands ###
